name: 'read-n-write-debug'

services:
  reader:
    image: reader-dev
    build:
      context: read-work-write
      dockerfile: ./Dockerfile
      target: development       
    volumes:
      - ./read-work-write:/home/node/app
    environment:
      NODE_ENV: development
      DEBUG: '*'
    ports:
      - 9229:9229
    command: ["run", "start:debug", "--", "--", "-p parameter1", "-p parameter2", "-w worker1", "-w worker2", "source", "target", "-w worker3"]
