name: 'read-n-write-debug'

services:
  reader:
    image: reader-dev
    build:
      context: read-work-write
      dockerfile: ./Dockerfile
      target: development       
    volumes:
      - ./read-work-write:/home/node/app
      - ./temp:/home/node/temp
    environment:
      NODE_ENV: development
      DEBUG: '*'   
    network_mode: host
    # command: ["run", "start:debug", "--", "--", "../temp/sample.txt", "../temp/copy.txt"]
    command: ["run", "start:debug", "--", "--", "../temp/sample.txt", "nats:4222/file-transfer", "--verbose"]
  writer:
    image: writer-dev
    build:
      context: read-work-write
      dockerfile: ./Dockerfile
      target: development       
    volumes:
      - ./read-work-write:/home/node/app
      - ./temp:/home/node/temp
    environment:
      NODE_ENV: development
      DEBUG: '*' 
    network_mode: host
    command: ["run", "start:dev", "--", "--", "nats:4222/file-transfer", "../temp/copy-over-nats-debug.txt", "-w slow", "--verbose"]
