name: 'read-n-write'

services:
  reader:
    image: reader
    build:
      context: read-work-write
      dockerfile: ./Dockerfile    
    environment:
      NODE_ENV: production
    command: ["-p parameter", "source", "target"]
