name: 'read-n-write-debug'

services:
  reader:
    image: reader-dev
    build:
      context: read-work-write
      dockerfile: ./Dockerfile
      target: development       
    volumes:
      - ./read-work-write:/home/node/app
      - ./temp:/home/node/temp
    environment:
      NODE_ENV: development
      DEBUG: '*'
    ports:
      - 9229:9229
    command: ["run", "start:debug", "--", "--", "../temp/sample.txt", "../temp/copy.txt"]
