name: 'read-n-write'

services:
  reader:
    image: reader
    build:
      context: reader
      dockerfile: ./Dockerfile    
    environment:
      NODE_ENV: production
    command: ["dist/main.js", "-p parameter", "source", "target"]
