name: 'read-n-write'

services:
  reader:
    image: reader
    build:
      context: read-work-write
      dockerfile: ./Dockerfile    
    environment:
      NODE_ENV: production
    command: ["-p parameter", "source", "target"]
  nats:
    image: nats:2.10.14-alpine3.19 # https://github.com/nats-io/nats-docker/blob/main/2.10.x/alpine3.19/
